### ISSUE TITLE
Use ReactDomServer.renderToString instead 

### ISSUE THREAD

**Issue by gutenye** [AlexMost/gulp-react-render#3]
React.renderToString has been moved to ReactDOMServer.renderToString, https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostring

**Comment by AlexMost** [comment]
good point will try to fix that soon

**Comment by AlexMost** [comment]
fixed https://github.com/AlexMost/gulp-react-render/commit/871f5aa85cf41b9e1bd3d411ff85d45d7a7d2981
